[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[client]
toolbarMode = "minimal"

[theme]
primaryColor = "#4CAF50"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"

[global]
gatherUsageStats = false
